/**
 * Generates the README screenshots under `docs/screenshots/` from the real,
 * built app — so the documentation shows the product, not a mock-up.
 *
 * Like `og-image.ts`, this is a one-off documentation asset, committed to the
 * repo and regenerated by hand (`npm run screenshots`) after a meaningful UI
 * change — it is NOT a build step and CI never runs it (so CI stays
 * Playwright-only in the dedicated e2e job). The images live in `docs/` rather
 * than `public/` so they ship with the README, not with the deployed site.
 *
 * It serves the production build over `vite preview` (the exact bytes that ship)
 * and drives a headless Chromium at a 2x device scale for crisp captures:
 *   - home.png        the home / anti-budget at a desktop width
 *   - all-tools.png   the crawlable All Tools index (the 59-calculator catalog)
 *   - cited-result.png  a calculator's answer + the cited "show the math" table
 *                       (the differentiator: every statutory line links its source)
 *   - mobile.png      the same computed result at a 390px phone width, evidencing
 *                     the no-horizontal-scroll responsiveness requirement
 *
 * Determinism note: every capture uses a tile's built-in "Try an example", so
 * the figures are the repo's own worked cases — no invented or personal data.
 */
import { chromium, type Browser } from "@playwright/test";
import { spawn, type ChildProcess } from "node:child_process";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { mkdir } from "node:fs/promises";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const OUT_DIR = resolve(ROOT, "docs", "screenshots");
const PORT = 4188;
const BASE = `http://localhost:${PORT}`;

/** Start `vite preview` over the built dist and resolve once it answers. */
async function startPreview(): Promise<ChildProcess> {
  const server = spawn("npx", ["vite", "preview", "--port", String(PORT), "--strictPort"], {
    cwd: ROOT,
    stdio: "ignore",
  });
  const deadline = Date.now() + 60_000;
  // Date.now() is fine here: this is a dev-time asset script, never resumed.
  for (;;) {
    try {
      const res = await fetch(`${BASE}/`);
      if (res.ok) return server;
    } catch {
      // not up yet
    }
    if (Date.now() > deadline) {
      server.kill("SIGKILL");
      throw new Error("vite preview did not start within 60s");
    }
    await new Promise((r) => setTimeout(r, 400));
  }
}

/** Navigate, run the worked example, and wait for the result to settle. */
async function withExample(
  browser: Browser,
  width: number,
  height: number,
  hash: string,
): Promise<{ page: Awaited<ReturnType<Browser["newPage"]>>; close: () => Promise<void> }> {
  const page = await browser.newPage({
    viewport: { width, height },
    deviceScaleFactor: 2,
  });
  await page.goto(`${BASE}/${hash}`, { waitUntil: "networkidle" });
  await page.waitForSelector(".content");
  const example = page.getByRole("button", { name: /example/i }).first();
  if (await example.isVisible().catch(() => false)) {
    await example.click();
    await page.waitForSelector(".result-value");
    // Let the count-up animation reach the final figure before capturing.
    await page.waitForTimeout(1200);
  }
  return { page, close: () => page.close() };
}

async function main(): Promise<void> {
  await mkdir(OUT_DIR, { recursive: true });
  const server = await startPreview();
  const browser = await chromium.launch();
  try {
    // 1) Home / anti-budget (desktop hero).
    {
      const page = await browser.newPage({
        viewport: { width: 1280, height: 880 },
        deviceScaleFactor: 2,
      });
      await page.goto(`${BASE}/#/`, { waitUntil: "networkidle" });
      await page.waitForSelector(".content");
      await page.waitForTimeout(400);
      await page.screenshot({ path: resolve(OUT_DIR, "home.png"), type: "png" });
      await page.close();
    }

    // 2) All Tools index (the catalog of 59 calculators in 10 hubs).
    {
      const page = await browser.newPage({
        viewport: { width: 1280, height: 880 },
        deviceScaleFactor: 2,
      });
      await page.goto(`${BASE}/#/all-tools`, { waitUntil: "networkidle" });
      await page.waitForSelector(".content");
      await page.waitForTimeout(400);
      await page.screenshot({ path: resolve(OUT_DIR, "all-tools.png"), type: "png" });
      await page.close();
    }

    // 3) A computed result with its cited breakdown (the "shows its math" shot).
    {
      const { page, close } = await withExample(
        browser,
        1024,
        1200,
        "#/paycheck-taxes?tool=federal-income-tax",
      );
      const card = page.locator(".result-card").first();
      await card.scrollIntoViewIfNeeded();
      await card.screenshot({ path: resolve(OUT_DIR, "cited-result.png"), type: "png" });
      await close();
    }

    // 4) The same result on a 390px phone — no horizontal scroll, still readable.
    {
      const { page, close } = await withExample(
        browser,
        390,
        844,
        "#/paycheck-taxes?tool=federal-income-tax",
      );
      await page.locator(".result-value").scrollIntoViewIfNeeded();
      await page.screenshot({ path: resolve(OUT_DIR, "mobile.png"), type: "png" });
      await close();
    }

    console.log(`Wrote home.png, all-tools.png, cited-result.png, mobile.png to ${OUT_DIR}`);
  } finally {
    await browser.close();
    server.kill("SIGKILL");
  }
}

void main();
